### ISSUE TITLE
Failed to activate the atom-language-rust package

### ISSUE THREAD

**Issue by Antiarchitect** [miqid/atom-language-rust#1]
Just upgraded to 0.4.0 from 0.3.x.

**Atom Version**: 1.5.3
**System**: "Fedora release
**Thrown From**: [atom-language-rust](https://github.com/miqid/atom-language-rust) package, v0.4.0

### Stack Trace

Failed to activate the atom-language-rust package

```
At Cannot read property 'add' of null

TypeError: Cannot read property 'add' of null
    at Rust.activate (/home/andrey/.atom/packages/atom-language-rust/lib/rust.js:70:4)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:181:20)
    at /usr/share/atom/resources/app.asar/src/package.js:155:32
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at /usr/share/atom/resources/app.asar/src/package.js:148:26
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:145:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:526:21)
    at /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:385:60
    at exit (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:213:47)
    at /usr/share/atom/resources/app.asar/src/buffered-process.js:227:18
    at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

### Commands

```
 32x -0:34.2.0 core:move-down (atom-text-editor.editor.is-focused)
 12x -0:27.9.0 core:move-up (atom-text-editor.editor.is-focused)
 34x -0:26.3.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:14.2.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {},
  "atom-language-rust": {
    "colors": {}
  }
}
```

### Installed Packages

```coffee
# User
atom-language-rust, v0.4.0

# Dev
No dev packages
```

**Comment by miqid** [comment]
Thanks for the report, I'll investigate.

In the meanwhile, does reinstalling the package alleviate the error? Also, did you have any custom colour values specified?

I've a feeling this has something to do with the new configuration option added to style documentation blocks.

**Comment by Antiarchitect** [comment]
There are no custom colour values for sure. It was plain atom installation and the first plugin I've installed on my new notebook and then upgraded. Full reinstall seems did the trick!

**Comment by miqid** [comment]
Glad to hear that a package reinstall resolved the error!

I've put through a fix that I believe will address the problem for future package upgrades. It'll make an appearance in the next release and will hopefully spare everybody from needing to do a reinstall.

**Comment by 35359595** [comment]
Hi, just had the same problem on Fedora 22.
Using it for quiet a while )
Reinstall of atom-language-rust nad restart of Atom fixed the issue for me.
