### ISSUE TITLE
Failed to activate the atom-language-rust package

### ISSUE THREAD

**Issue by edubenetskiy** [miqid/atom-language-rust#8]
### Steps to reproduce

1. Start up a fresh Atom installation.
2. Install `atom-language-rust` package.
3. See it tries to get enabled automatically.
4. Get this error.

Restarting Atom and reinstalling the package (as suggested the conversation for #1) brought no effect. The bug remains.

### System information

**Atom Version**: 1.9.8
**System**: linux 4.7.0-1-ARCH
**Thrown From**: [atom-language-rust](https://github.com/miqid/atom-language-rust) package, v0.8.1

Atom was installed via `pacman` from the `community` repository. 
The `atom-language-rust` package was installed using the **Settings → Install** menu.

### Stack Trace

Failed to activate the atom-language-rust package

```
Path must be a string. Received null

TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at extname (path.js:1433:5)
    at LessCache.module.exports.LessCache.getCachePath (/usr/lib/atom/node_modules/less-cache/lib/less-cache.js:178:44)
    at LessCache.module.exports.LessCache.putCachedCss (/usr/lib/atom/node_modules/less-cache/lib/less-cache.js:238:27)
    at LessCache.module.exports.LessCache.cssForFile (/usr/lib/atom/node_modules/less-cache/lib/less-cache.js:287:12)
    at LessCompileCache.module.exports.LessCompileCache.cssForFile (/usr/lib/atom/src/less-compile-cache.js:40:25)
    at Rust.readDefaultColors (/home/edubenetskiy/.atom/packages/atom-language-rust/lib/rust.js:132:29)
    at Rust.activate (/home/edubenetskiy/.atom/packages/atom-language-rust/lib/rust.js:79:10)
    at Package.module.exports.Package.activateNow (/usr/lib/atom/src/package.js:183:20)
    at /usr/lib/atom/src/package.js:156:32
    at Package.module.exports.Package.measure (/usr/lib/atom/src/package.js:92:15)
    at /usr/lib/atom/src/package.js:149:26
    at Package.module.exports.Package.activate (/usr/lib/atom/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/lib/atom/src/package-manager.js:530:21)
    at /usr/lib/atom/src/package-manager.js:334:19
    at /usr/lib/atom/src/config.js:631:20
    at Function.module.exports.Emitter.simpleDispatch (/usr/lib/atom/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/lib/atom/node_modules/event-kit/lib/emitter.js:125:28)
    at Config.module.exports.Config.emitChangeEvent (/usr/lib/atom/src/config.js:816:29)
    at Config.module.exports.Config.setRawValue (/usr/lib/atom/src/config.js:608:19)
    at Config.module.exports.Config.set (/usr/lib/atom/src/config.js:227:14)
    at Config.module.exports.Config.removeAtKeyPath (/usr/lib/atom/src/config.js:377:12)
    at Package.module.exports.Package.enable (/usr/lib/atom/src/package.js:77:26)
    at PackageManager.module.exports.PackageManager.enablePackage (/usr/lib/atom/src/package-manager.js:161:14)
    at HTMLButtonElement.<anonymous> (/usr/lib/atom/node_modules/settings-view/lib/package-card.js:324:27)
    at HTMLButtonElement.dispatch (/usr/lib/atom/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/usr/lib/atom/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -1:23 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -1:23 core:cancel (atom-text-editor.editor.mini.is-focused)
     -1:21.9.0 symbols-view:go-to-declaration (atom-text-editor.editor.is-focused)
     -1:19.9.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -1:15.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:15.8.0 symbols-view:go-to-declaration (atom-text-editor.editor)
     -1:15.1.0 core:move-right (atom-text-editor.editor.is-focused)
     -1:14 command-palette:toggle (atom-text-editor.editor.is-focused)
     -1:12.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
 11x -1:10.2.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -1:07.3.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -1:05.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:05.0 rustfmt:format (atom-text-editor.editor)
     -1:03.1.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -1:01.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:01.4.0 racer:find-definition (atom-text-editor.editor)
```

### Config

```json
{
  "core": {},
  "atom-language-rust": {
    "colors": {}
  }
}
```

### Installed Packages

```coffee
# User
atom-language-rust, v0.8.1 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (active)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (active)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
find-and-replace, v0.198.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.46.0 (active)
symbols-view, v0.113.0 (active)
tabs, v0.98.1 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by miqid** [comment]
Is there any chance that you could try installing Atom from AUR instead (i.e. https://aur.archlinux.org/atom-editor.git) and seeing whether this problem still persists? Please provide the output of `atom --version` for your current installation too.

After searching through some posts, I'm inclined to believe that the version of Atom provided by the `community` repository is packaged using a version of Electron that still doesn't have official support (c.f. https://github.com/atom/atom/pull/12300), which apparently causes undesirable behaviour in the editor.

**Comment by nbigaouette** [comment]
I just saw that atom was now in community, so removed my `atom-editor` version 1.9.8 from AUR and installed 1.9.9-1 from community. I now see this problem, which was absent before.

**Comment by edubenetskiy** [comment]
The one from `community`:

```
$ atom --version
Atom    : 1.9.8
Electron: 1.3.3
Chrome  : 52.0.2743.82
Node    : 6.3.0
```

**Comment by nbigaouette** [comment]
See this discussion for problems with the package community: https://bugs.archlinux.org/task/50357

From what I get from it, the version in community has a different (newer?) version of electron, which breaks many things.

**Comment by edubenetskiy** [comment]
Trying to update from `community` (my system upgrade will bring Atom 1.9.9-1 and Electron 1.3.3-2), then I'll attempt to install Atom from AUR.

**Comment by edubenetskiy** [comment]
I have upgraded Atom & Electron from `community`.

```
$ atom --version
Atom    : 1.9.9
Electron: 1.3.3
Chrome  : 52.0.2743.82
Node    : 6.3.0
```

The bug did not vanish.

**Comment by edubenetskiy** [comment]
Installed `atom-editor` from AUR. Everything works fine.

```
$ atom --version
Atom    : 1.9.9
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
```

Obviously, it is better to use AUR version of the package, and this is the way I am going to run and upgrade my Atom installation. But the fact that the dependencies of that officially distributed `community` version are not adjusted adequately can be disappointing.

**Comment by miqid** [comment]
Thank you for the updates @edubenetskiy.

I've made a small change that I think will resolve the problem you've reported. I quickly tested it by spinning up a VM with an ArchLinux installation and I didn't see the error being thrown. Try updating to [0.9.0](https://github.com/miqid/atom-language-rust/releases/tag/0.9.0) and letting me know of your results.

**Comment by edubenetskiy** [comment]
Installed the notorious `community` version of Atom and successfully updated `atom-language-rust`. The error message disappeared, and syntax highlighting, package configuration etc. are working properly. Good job! Much obliged for your responsible attitude and resolving such an error which is surely caused not by you. Thank you, @miqid!
